[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
derp_contracts = "GZeLk7wqD1MUk2ELdMw4KskogNQsckoVqCTCbepxT1h3"

[programs.devnet]
derp_contracts = "GZeLk7wqD1MUk2ELdMw4KskogNQsckoVqCTCbepxT1h3"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Devnet"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "2uPQGpm8X4ZkxMHxrAW1QuhXcse1AHEgPih6Xp9NuEWW"
[[test.validator.clone]]
address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"
[[test.validator.clone]]
address = "2t8eUbYKjidMs3uSeYM9jXM9uudYZwGkSeTB4TKjmvnC"